/*
 * Lcd.h
 *
 *  Created on: Mar 15, 2022
 *      Author: Ahmed-Yehia
 */

#ifndef LCD_H_
#define LCD_H_

#define LCD_u8CMD__CLR_DISPLAY                              0x01
#define LCD_u8CMD__RTN_HOME                                 0x02

#define LCD_u8CMD__CURSOR_DEC_SCEERN_SHIFT_OFF              0x04
#define LCD_u8CMD__CURSOR_DEC_SCEERN_SHIFT_ON               0x05
#define LCD_u8CMD__CURSOR_INC_SCEERN_SHIFT_OFF              0x06
#define LCD_u8CMD__CURSOR_INC_SCEERN_SHIFT_ON               0x07

#define LCD_u8CMD__DISPLAY_OFF                              0x08
#define LCD_u8CMD__DISPLAY_ON_CURSOR_OFF                    0x0C
#define LCD_u8CMD__DISPLAY_ON_CURSOR_ON_BLINK_OFF           0x0E
#define LCD_u8CMD__DISPLAY_ON_CURSOR_ON_BLINK_ON            0x0F

#define LCD_u8CMD__CURSOR_SHFT_LEFT                         0x10
#define LCD_u8CMD__CURSOR_SHFT_RIGHT                        0x14
#define LCD_u8CMD__DISPLAY_SHFT_LEFT                        0x18
#define LCD_u8CMD__DISPLAY_SHFT_RIGHT                       0x1C

#define LCD_u8CMD__MODE_4_BIT_1_LINE_5_7_FONT               0x20
#define LCD_u8CMD__MODE_4_BIT_1_LINE_5_10_FONT              0x24
#define LCD_u8CMD__MODE_4_BIT_2_LINE_5_7_FONT               0x28
#define LCD_u8CMD__MODE_4_BIT_2_LINE_5_10_FONT              0x2C
#define LCD_u8CMD__MODE_8_BIT_1_LINE_5_7_FONT               0x30
#define LCD_u8CMD__MODE_8_BIT_1_LINE_5_10_FONT              0x34
#define LCD_u8CMD__MODE_8_BIT_2_LINE_5_7_FONT               0x38
#define LCD_u8CMD__MODE_8_BIT_2_LINE_5_10_FONT              0x3C

#define LCD_u8CMD__CG_RAM_SHAPE_0                           0x40
#define LCD_u8CMD__CG_RAM_SHAPE_1                           0x48
#define LCD_u8CMD__CG_RAM_SHAPE_2                           0x50
#define LCD_u8CMD__CG_RAM_SHAPE_3                           0x58
#define LCD_u8CMD__CG_RAM_SHAPE_4                           0x60
#define LCD_u8CMD__CG_RAM_SHAPE_5                           0x68
#define LCD_u8CMD__CG_RAM_SHAPE_6                           0x70
#define LCD_u8CMD__CG_RAM_SHAPE_7                           0x78

// DD RAM addresses 
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_0                  0x80
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_1                  0x81
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_2                  0x82
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_3                  0x83
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_4                  0x84
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_5                  0x85
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_6                  0x86
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_7                  0x87
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_8                  0x88
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_9                  0x89
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_10                 0x8A
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_11                 0x8B
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_12                 0x8C
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_13                 0x8D
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_14                 0x8E
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_15                 0x8F
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_16                 0x90
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_17                 0x91
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_18                 0x92
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_19                 0x93
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_20                 0x94
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_21                 0x95
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_22                 0x96
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_23                 0x97
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_24                 0x98
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_25                 0x99
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_26                 0x9A
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_27                 0x9B
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_28                 0x9C
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_29                 0x9D
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_30                 0x9E
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_31                 0x9F
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_32                 0xA0
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_33                 0xA1
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_34                 0xA2
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_35                 0xA3
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_36                 0xA4
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_37                 0xA5
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_38                 0xA6
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_39                 0xA7
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_40                 0xA8
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_41                 0xA9
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_42                 0xAA
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_43                 0xAB
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_44                 0xAC
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_45                 0xAD
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_46                 0xAE
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_47                 0xAF
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_48                 0xB0
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_49                 0xB1
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_50                 0xB2
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_51                 0xB3
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_52                 0xB4
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_53                 0xB5
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_54                 0xB6
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_55                 0xB7
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_56                 0xB8
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_57                 0xB9
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_58                 0xBA
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_59                 0xBB
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_60                 0xBC
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_61                 0xBD
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_62                 0xBE
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_63                 0xBF
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_64                 0xC0
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_65                 0xC1
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_66                 0xC2
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_67                 0xC3
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_68                 0xC4
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_69                 0xC5
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_70                 0xC6
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_71                 0xC7
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_72                 0xC8
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_73                 0xC9
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_74                 0xCA
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_75                 0xCB
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_76                 0xCC
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_77                 0xCD
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_78                 0xCE
#define LCD_u8CMD__DD_RAM_1_LINE_ADDRESS_79                 0xCF

#define LCD_u8CMD__DD_RAM_2_LINES_LINE1_ADDRESS_0           0x80
#define LCD_u8CMD__DD_RAM_2_LINES_LINE1_ADDRESS_1           0x81
#define LCD_u8CMD__DD_RAM_2_LINES_LINE1_ADDRESS_2           0x82
#define LCD_u8CMD__DD_RAM_2_LINES_LINE1_ADDRESS_3           0x83
#define LCD_u8CMD__DD_RAM_2_LINES_LINE1_ADDRESS_4           0x84
#define LCD_u8CMD__DD_RAM_2_LINES_LINE1_ADDRESS_5           0x85
#define LCD_u8CMD__DD_RAM_2_LINES_LINE1_ADDRESS_6           0x86
#define LCD_u8CMD__DD_RAM_2_LINES_LINE1_ADDRESS_7           0x87
#define LCD_u8CMD__DD_RAM_2_LINES_LINE1_ADDRESS_8           0x88
#define LCD_u8CMD__DD_RAM_2_LINES_LINE1_ADDRESS_9           0x89
#define LCD_u8CMD__DD_RAM_2_LINES_LINE1_ADDRESS_10          0x8A
#define LCD_u8CMD__DD_RAM_2_LINES_LINE1_ADDRESS_11          0x8B
#define LCD_u8CMD__DD_RAM_2_LINES_LINE1_ADDRESS_12          0x8C
#define LCD_u8CMD__DD_RAM_2_LINES_LINE1_ADDRESS_13          0x8D
#define LCD_u8CMD__DD_RAM_2_LINES_LINE1_ADDRESS_14          0x8E
#define LCD_u8CMD__DD_RAM_2_LINES_LINE1_ADDRESS_15          0x8F
#define LCD_u8CMD__DD_RAM_2_LINES_LINE1_ADDRESS_16          0x90
#define LCD_u8CMD__DD_RAM_2_LINES_LINE1_ADDRESS_17          0x91
#define LCD_u8CMD__DD_RAM_2_LINES_LINE1_ADDRESS_18          0x92
#define LCD_u8CMD__DD_RAM_2_LINES_LINE1_ADDRESS_19          0x93
#define LCD_u8CMD__DD_RAM_2_LINES_LINE1_ADDRESS_20          0x94
#define LCD_u8CMD__DD_RAM_2_LINES_LINE1_ADDRESS_21          0x95
#define LCD_u8CMD__DD_RAM_2_LINES_LINE1_ADDRESS_22          0x96
#define LCD_u8CMD__DD_RAM_2_LINES_LINE1_ADDRESS_23          0x97
#define LCD_u8CMD__DD_RAM_2_LINES_LINE1_ADDRESS_24          0x98
#define LCD_u8CMD__DD_RAM_2_LINES_LINE1_ADDRESS_25          0x99
#define LCD_u8CMD__DD_RAM_2_LINES_LINE1_ADDRESS_26          0x9A
#define LCD_u8CMD__DD_RAM_2_LINES_LINE1_ADDRESS_27          0x9B
#define LCD_u8CMD__DD_RAM_2_LINES_LINE1_ADDRESS_28          0x9C
#define LCD_u8CMD__DD_RAM_2_LINES_LINE1_ADDRESS_29          0x9D
#define LCD_u8CMD__DD_RAM_2_LINES_LINE1_ADDRESS_30          0x9E
#define LCD_u8CMD__DD_RAM_2_LINES_LINE1_ADDRESS_31          0x9F
#define LCD_u8CMD__DD_RAM_2_LINES_LINE1_ADDRESS_32          0xA0
#define LCD_u8CMD__DD_RAM_2_LINES_LINE1_ADDRESS_33          0xA1
#define LCD_u8CMD__DD_RAM_2_LINES_LINE1_ADDRESS_34          0xA2
#define LCD_u8CMD__DD_RAM_2_LINES_LINE1_ADDRESS_35          0xA3
#define LCD_u8CMD__DD_RAM_2_LINES_LINE1_ADDRESS_36          0xA4
#define LCD_u8CMD__DD_RAM_2_LINES_LINE1_ADDRESS_37          0xA5
#define LCD_u8CMD__DD_RAM_2_LINES_LINE1_ADDRESS_38          0xA6
#define LCD_u8CMD__DD_RAM_2_LINES_LINE1_ADDRESS_39          0xA7

#define LCD_u8CMD__DD_RAM_2_LINES_LINE2_ADDRESS_0           0xC0
#define LCD_u8CMD__DD_RAM_2_LINES_LINE2_ADDRESS_1           0xC1
#define LCD_u8CMD__DD_RAM_2_LINES_LINE2_ADDRESS_2           0xC2
#define LCD_u8CMD__DD_RAM_2_LINES_LINE2_ADDRESS_3           0xC3
#define LCD_u8CMD__DD_RAM_2_LINES_LINE2_ADDRESS_4           0xC4
#define LCD_u8CMD__DD_RAM_2_LINES_LINE2_ADDRESS_5           0xC5
#define LCD_u8CMD__DD_RAM_2_LINES_LINE2_ADDRESS_6           0xC6
#define LCD_u8CMD__DD_RAM_2_LINES_LINE2_ADDRESS_7           0xC7
#define LCD_u8CMD__DD_RAM_2_LINES_LINE2_ADDRESS_8           0xC8
#define LCD_u8CMD__DD_RAM_2_LINES_LINE2_ADDRESS_9           0xC9
#define LCD_u8CMD__DD_RAM_2_LINES_LINE2_ADDRESS_10          0xCA
#define LCD_u8CMD__DD_RAM_2_LINES_LINE2_ADDRESS_11          0xCB
#define LCD_u8CMD__DD_RAM_2_LINES_LINE2_ADDRESS_12          0xCC
#define LCD_u8CMD__DD_RAM_2_LINES_LINE2_ADDRESS_13          0xCD
#define LCD_u8CMD__DD_RAM_2_LINES_LINE2_ADDRESS_14          0xCE
#define LCD_u8CMD__DD_RAM_2_LINES_LINE2_ADDRESS_15          0xCF
#define LCD_u8CMD__DD_RAM_2_LINES_LINE2_ADDRESS_16          0xD0
#define LCD_u8CMD__DD_RAM_2_LINES_LINE2_ADDRESS_17          0xD1
#define LCD_u8CMD__DD_RAM_2_LINES_LINE2_ADDRESS_18          0xD2
#define LCD_u8CMD__DD_RAM_2_LINES_LINE2_ADDRESS_19          0xD3
#define LCD_u8CMD__DD_RAM_2_LINES_LINE2_ADDRESS_20          0xD4
#define LCD_u8CMD__DD_RAM_2_LINES_LINE2_ADDRESS_21          0xD5
#define LCD_u8CMD__DD_RAM_2_LINES_LINE2_ADDRESS_22          0xD6
#define LCD_u8CMD__DD_RAM_2_LINES_LINE2_ADDRESS_23          0xD7
#define LCD_u8CMD__DD_RAM_2_LINES_LINE2_ADDRESS_24          0xD8
#define LCD_u8CMD__DD_RAM_2_LINES_LINE2_ADDRESS_25          0xD9
#define LCD_u8CMD__DD_RAM_2_LINES_LINE2_ADDRESS_26          0xDA
#define LCD_u8CMD__DD_RAM_2_LINES_LINE2_ADDRESS_27          0xDB
#define LCD_u8CMD__DD_RAM_2_LINES_LINE2_ADDRESS_28          0xDC
#define LCD_u8CMD__DD_RAM_2_LINES_LINE2_ADDRESS_29          0xDD
#define LCD_u8CMD__DD_RAM_2_LINES_LINE2_ADDRESS_30          0xDE
#define LCD_u8CMD__DD_RAM_2_LINES_LINE2_ADDRESS_31          0xDF
#define LCD_u8CMD__DD_RAM_2_LINES_LINE2_ADDRESS_32          0xE0
#define LCD_u8CMD__DD_RAM_2_LINES_LINE2_ADDRESS_33          0xE1
#define LCD_u8CMD__DD_RAM_2_LINES_LINE2_ADDRESS_34          0xE2
#define LCD_u8CMD__DD_RAM_2_LINES_LINE2_ADDRESS_35          0xE3
#define LCD_u8CMD__DD_RAM_2_LINES_LINE2_ADDRESS_36          0xE4
#define LCD_u8CMD__DD_RAM_2_LINES_LINE2_ADDRESS_37          0xE5
#define LCD_u8CMD__DD_RAM_2_LINES_LINE2_ADDRESS_38          0xE6
#define LCD_u8CMD__DD_RAM_2_LINES_LINE2_ADDRESS_39          0xE7

#define LCD_u8DATA__XX_RAM_DATA_0                           0x00
#define LCD_u8DATA__XX_RAM_DATA_1                           0x01
#define LCD_u8DATA__XX_RAM_DATA_2                           0x02
#define LCD_u8DATA__XX_RAM_DATA_3                           0x03
#define LCD_u8DATA__XX_RAM_DATA_4                           0x04
#define LCD_u8DATA__XX_RAM_DATA_5                           0x05
#define LCD_u8DATA__XX_RAM_DATA_6                           0x06
#define LCD_u8DATA__XX_RAM_DATA_7                           0x07
#define LCD_u8DATA__XX_RAM_DATA_8                           0x08
#define LCD_u8DATA__XX_RAM_DATA_9                           0x09
#define LCD_u8DATA__XX_RAM_DATA_10                          0x0A
#define LCD_u8DATA__XX_RAM_DATA_11                          0x0B
#define LCD_u8DATA__XX_RAM_DATA_12                          0x0C
#define LCD_u8DATA__XX_RAM_DATA_13                          0x0D
#define LCD_u8DATA__XX_RAM_DATA_14                          0x0E
#define LCD_u8DATA__XX_RAM_DATA_15                          0x0F
#define LCD_u8DATA__XX_RAM_DATA_16                          0x10
#define LCD_u8DATA__XX_RAM_DATA_17                          0x11
#define LCD_u8DATA__XX_RAM_DATA_18                          0x12
#define LCD_u8DATA__XX_RAM_DATA_19                          0x13
#define LCD_u8DATA__XX_RAM_DATA_20                          0x14
#define LCD_u8DATA__XX_RAM_DATA_21                          0x15
#define LCD_u8DATA__XX_RAM_DATA_22                          0x16
#define LCD_u8DATA__XX_RAM_DATA_23                          0x17
#define LCD_u8DATA__XX_RAM_DATA_24                          0x18
#define LCD_u8DATA__XX_RAM_DATA_25                          0x19
#define LCD_u8DATA__XX_RAM_DATA_26                          0x1A
#define LCD_u8DATA__XX_RAM_DATA_27                          0x1B
#define LCD_u8DATA__XX_RAM_DATA_28                          0x1C
#define LCD_u8DATA__XX_RAM_DATA_29                          0x1D
#define LCD_u8DATA__XX_RAM_DATA_30                          0x1E
#define LCD_u8DATA__XX_RAM_DATA_31                          0x1F
#define LCD_u8DATA__XX_RAM_DATA_32                          0x20
#define LCD_u8DATA__XX_RAM_DATA_33                          0x21
#define LCD_u8DATA__XX_RAM_DATA_34                          0x22
#define LCD_u8DATA__XX_RAM_DATA_35                          0x23
#define LCD_u8DATA__XX_RAM_DATA_36                          0x24
#define LCD_u8DATA__XX_RAM_DATA_37                          0x25
#define LCD_u8DATA__XX_RAM_DATA_38                          0x26
#define LCD_u8DATA__XX_RAM_DATA_39                          0x27
#define LCD_u8DATA__XX_RAM_DATA_40                          0x28
#define LCD_u8DATA__XX_RAM_DATA_41                          0x29
#define LCD_u8DATA__XX_RAM_DATA_42                          0x2A
#define LCD_u8DATA__XX_RAM_DATA_43                          0x2B
#define LCD_u8DATA__XX_RAM_DATA_44                          0x2C
#define LCD_u8DATA__XX_RAM_DATA_45                          0x2D
#define LCD_u8DATA__XX_RAM_DATA_46                          0x2E
#define LCD_u8DATA__XX_RAM_DATA_47                          0x2F
#define LCD_u8DATA__XX_RAM_DATA_48                          0x30
#define LCD_u8DATA__XX_RAM_DATA_49                          0x31
#define LCD_u8DATA__XX_RAM_DATA_50                          0x32
#define LCD_u8DATA__XX_RAM_DATA_51                          0x33
#define LCD_u8DATA__XX_RAM_DATA_52                          0x34
#define LCD_u8DATA__XX_RAM_DATA_53                          0x35
#define LCD_u8DATA__XX_RAM_DATA_54                          0x36
#define LCD_u8DATA__XX_RAM_DATA_55                          0x37
#define LCD_u8DATA__XX_RAM_DATA_56                          0x38
#define LCD_u8DATA__XX_RAM_DATA_57                          0x39
#define LCD_u8DATA__XX_RAM_DATA_58                          0x3A
#define LCD_u8DATA__XX_RAM_DATA_59                          0x3B
#define LCD_u8DATA__XX_RAM_DATA_60                          0x3C
#define LCD_u8DATA__XX_RAM_DATA_61                          0x3D
#define LCD_u8DATA__XX_RAM_DATA_62                          0x3E
#define LCD_u8DATA__XX_RAM_DATA_63                          0x3F
#define LCD_u8DATA__XX_RAM_DATA_64                          0x40
#define LCD_u8DATA__XX_RAM_DATA_65                          0x41
#define LCD_u8DATA__XX_RAM_DATA_66                          0x42
#define LCD_u8DATA__XX_RAM_DATA_67                          0x43
#define LCD_u8DATA__XX_RAM_DATA_68                          0x44
#define LCD_u8DATA__XX_RAM_DATA_69                          0x45
#define LCD_u8DATA__XX_RAM_DATA_70                          0x46
#define LCD_u8DATA__XX_RAM_DATA_71                          0x47
#define LCD_u8DATA__XX_RAM_DATA_72                          0x48
#define LCD_u8DATA__XX_RAM_DATA_73                          0x49
#define LCD_u8DATA__XX_RAM_DATA_74                          0x4A
#define LCD_u8DATA__XX_RAM_DATA_75                          0x4B
#define LCD_u8DATA__XX_RAM_DATA_76                          0x4C
#define LCD_u8DATA__XX_RAM_DATA_77                          0x4D
#define LCD_u8DATA__XX_RAM_DATA_78                          0x4E
#define LCD_u8DATA__XX_RAM_DATA_79                          0x4F
#define LCD_u8DATA__XX_RAM_DATA_80                          0x50
#define LCD_u8DATA__XX_RAM_DATA_81                          0x51
#define LCD_u8DATA__XX_RAM_DATA_82                          0x52
#define LCD_u8DATA__XX_RAM_DATA_83                          0x53
#define LCD_u8DATA__XX_RAM_DATA_84                          0x54
#define LCD_u8DATA__XX_RAM_DATA_85                          0x55
#define LCD_u8DATA__XX_RAM_DATA_86                          0x56
#define LCD_u8DATA__XX_RAM_DATA_87                          0x57
#define LCD_u8DATA__XX_RAM_DATA_88                          0x58
#define LCD_u8DATA__XX_RAM_DATA_89                          0x59
#define LCD_u8DATA__XX_RAM_DATA_90                          0x5A
#define LCD_u8DATA__XX_RAM_DATA_91                          0x5B
#define LCD_u8DATA__XX_RAM_DATA_92                          0x5C
#define LCD_u8DATA__XX_RAM_DATA_93                          0x5D
#define LCD_u8DATA__XX_RAM_DATA_94                          0x5E
#define LCD_u8DATA__XX_RAM_DATA_95                          0x5F
#define LCD_u8DATA__XX_RAM_DATA_96                          0x60
#define LCD_u8DATA__XX_RAM_DATA_97                          0x61
#define LCD_u8DATA__XX_RAM_DATA_98                          0x62
#define LCD_u8DATA__XX_RAM_DATA_99                          0x63
#define LCD_u8DATA__XX_RAM_DATA_100                         0x64
#define LCD_u8DATA__XX_RAM_DATA_101                         0x65
#define LCD_u8DATA__XX_RAM_DATA_102                         0x66
#define LCD_u8DATA__XX_RAM_DATA_103                         0x67
#define LCD_u8DATA__XX_RAM_DATA_104                         0x68
#define LCD_u8DATA__XX_RAM_DATA_105                         0x69
#define LCD_u8DATA__XX_RAM_DATA_106                         0x6A
#define LCD_u8DATA__XX_RAM_DATA_107                         0x6B
#define LCD_u8DATA__XX_RAM_DATA_108                         0x6C
#define LCD_u8DATA__XX_RAM_DATA_109                         0x6D
#define LCD_u8DATA__XX_RAM_DATA_110                         0x6E
#define LCD_u8DATA__XX_RAM_DATA_111                         0x6F
#define LCD_u8DATA__XX_RAM_DATA_112                         0x70
#define LCD_u8DATA__XX_RAM_DATA_113                         0x71
#define LCD_u8DATA__XX_RAM_DATA_114                         0x72
#define LCD_u8DATA__XX_RAM_DATA_115                         0x73
#define LCD_u8DATA__XX_RAM_DATA_116                         0x74
#define LCD_u8DATA__XX_RAM_DATA_117                         0x75
#define LCD_u8DATA__XX_RAM_DATA_118                         0x76
#define LCD_u8DATA__XX_RAM_DATA_119                         0x77
#define LCD_u8DATA__XX_RAM_DATA_120                         0x78
#define LCD_u8DATA__XX_RAM_DATA_121                         0x79
#define LCD_u8DATA__XX_RAM_DATA_122                         0x7A
#define LCD_u8DATA__XX_RAM_DATA_123                         0x7B
#define LCD_u8DATA__XX_RAM_DATA_124                         0x7C
#define LCD_u8DATA__XX_RAM_DATA_125                         0x7D
#define LCD_u8DATA__XX_RAM_DATA_126                         0x7E
#define LCD_u8DATA__XX_RAM_DATA_127                         0x7F
#define LCD_u8DATA__XX_RAM_DATA_128                         0x80
#define LCD_u8DATA__XX_RAM_DATA_129                         0x81
#define LCD_u8DATA__XX_RAM_DATA_130                         0x82
#define LCD_u8DATA__XX_RAM_DATA_131                         0x83
#define LCD_u8DATA__XX_RAM_DATA_132                         0x84
#define LCD_u8DATA__XX_RAM_DATA_133                         0x85
#define LCD_u8DATA__XX_RAM_DATA_134                         0x86
#define LCD_u8DATA__XX_RAM_DATA_135                         0x87
#define LCD_u8DATA__XX_RAM_DATA_136                         0x88
#define LCD_u8DATA__XX_RAM_DATA_137                         0x89
#define LCD_u8DATA__XX_RAM_DATA_138                         0x8A
#define LCD_u8DATA__XX_RAM_DATA_139                         0x8B
#define LCD_u8DATA__XX_RAM_DATA_140                         0x8C
#define LCD_u8DATA__XX_RAM_DATA_141                         0x8D
#define LCD_u8DATA__XX_RAM_DATA_142                         0x8E
#define LCD_u8DATA__XX_RAM_DATA_143                         0x8F
#define LCD_u8DATA__XX_RAM_DATA_144                         0x90
#define LCD_u8DATA__XX_RAM_DATA_145                         0x91
#define LCD_u8DATA__XX_RAM_DATA_146                         0x92
#define LCD_u8DATA__XX_RAM_DATA_147                         0x93
#define LCD_u8DATA__XX_RAM_DATA_148                         0x94
#define LCD_u8DATA__XX_RAM_DATA_149                         0x95
#define LCD_u8DATA__XX_RAM_DATA_150                         0x96
#define LCD_u8DATA__XX_RAM_DATA_151                         0x97
#define LCD_u8DATA__XX_RAM_DATA_152                         0x98
#define LCD_u8DATA__XX_RAM_DATA_153                         0x99
#define LCD_u8DATA__XX_RAM_DATA_154                         0x9A
#define LCD_u8DATA__XX_RAM_DATA_155                         0x9B
#define LCD_u8DATA__XX_RAM_DATA_156                         0x9C
#define LCD_u8DATA__XX_RAM_DATA_157                         0x9D
#define LCD_u8DATA__XX_RAM_DATA_158                         0x9E
#define LCD_u8DATA__XX_RAM_DATA_159                         0x9F
#define LCD_u8DATA__XX_RAM_DATA_160                         0xA0
#define LCD_u8DATA__XX_RAM_DATA_161                         0xA1
#define LCD_u8DATA__XX_RAM_DATA_162                         0xA2
#define LCD_u8DATA__XX_RAM_DATA_163                         0xA3
#define LCD_u8DATA__XX_RAM_DATA_164                         0xA4
#define LCD_u8DATA__XX_RAM_DATA_165                         0xA5
#define LCD_u8DATA__XX_RAM_DATA_166                         0xA6
#define LCD_u8DATA__XX_RAM_DATA_167                         0xA7
#define LCD_u8DATA__XX_RAM_DATA_168                         0xA8
#define LCD_u8DATA__XX_RAM_DATA_169                         0xA9
#define LCD_u8DATA__XX_RAM_DATA_170                         0xAA
#define LCD_u8DATA__XX_RAM_DATA_171                         0xAB
#define LCD_u8DATA__XX_RAM_DATA_172                         0xAC
#define LCD_u8DATA__XX_RAM_DATA_173                         0xAD
#define LCD_u8DATA__XX_RAM_DATA_174                         0xAE
#define LCD_u8DATA__XX_RAM_DATA_175                         0xAF
#define LCD_u8DATA__XX_RAM_DATA_176                         0xB0
#define LCD_u8DATA__XX_RAM_DATA_177                         0xB1
#define LCD_u8DATA__XX_RAM_DATA_178                         0xB2
#define LCD_u8DATA__XX_RAM_DATA_179                         0xB3
#define LCD_u8DATA__XX_RAM_DATA_180                         0xB4
#define LCD_u8DATA__XX_RAM_DATA_181                         0xB5
#define LCD_u8DATA__XX_RAM_DATA_182                         0xB6
#define LCD_u8DATA__XX_RAM_DATA_183                         0xB7
#define LCD_u8DATA__XX_RAM_DATA_184                         0xB8
#define LCD_u8DATA__XX_RAM_DATA_185                         0xB9
#define LCD_u8DATA__XX_RAM_DATA_186                         0xBA
#define LCD_u8DATA__XX_RAM_DATA_187                         0xBB
#define LCD_u8DATA__XX_RAM_DATA_188                         0xBC
#define LCD_u8DATA__XX_RAM_DATA_189                         0xBD
#define LCD_u8DATA__XX_RAM_DATA_190                         0xBE
#define LCD_u8DATA__XX_RAM_DATA_191                         0xBF
#define LCD_u8DATA__XX_RAM_DATA_192                         0xC0
#define LCD_u8DATA__XX_RAM_DATA_193                         0xC1
#define LCD_u8DATA__XX_RAM_DATA_194                         0xC2
#define LCD_u8DATA__XX_RAM_DATA_195                         0xC3
#define LCD_u8DATA__XX_RAM_DATA_196                         0xC4
#define LCD_u8DATA__XX_RAM_DATA_197                         0xC5
#define LCD_u8DATA__XX_RAM_DATA_198                         0xC6
#define LCD_u8DATA__XX_RAM_DATA_199                         0xC7
#define LCD_u8DATA__XX_RAM_DATA_200                         0xC8
#define LCD_u8DATA__XX_RAM_DATA_201                         0xC9
#define LCD_u8DATA__XX_RAM_DATA_202                         0xCA
#define LCD_u8DATA__XX_RAM_DATA_203                         0xCB
#define LCD_u8DATA__XX_RAM_DATA_204                         0xCC
#define LCD_u8DATA__XX_RAM_DATA_205                         0xCD
#define LCD_u8DATA__XX_RAM_DATA_206                         0xCE
#define LCD_u8DATA__XX_RAM_DATA_207                         0xCF
#define LCD_u8DATA__XX_RAM_DATA_208                         0xD0
#define LCD_u8DATA__XX_RAM_DATA_209                         0xD1
#define LCD_u8DATA__XX_RAM_DATA_210                         0xD2
#define LCD_u8DATA__XX_RAM_DATA_211                         0xD3
#define LCD_u8DATA__XX_RAM_DATA_212                         0xD4
#define LCD_u8DATA__XX_RAM_DATA_213                         0xD5
#define LCD_u8DATA__XX_RAM_DATA_214                         0xD6
#define LCD_u8DATA__XX_RAM_DATA_215                         0xD7
#define LCD_u8DATA__XX_RAM_DATA_216                         0xD8
#define LCD_u8DATA__XX_RAM_DATA_217                         0xD9
#define LCD_u8DATA__XX_RAM_DATA_218                         0xDA
#define LCD_u8DATA__XX_RAM_DATA_219                         0xDB
#define LCD_u8DATA__XX_RAM_DATA_220                         0xDC
#define LCD_u8DATA__XX_RAM_DATA_221                         0xDD
#define LCD_u8DATA__XX_RAM_DATA_222                         0xDE
#define LCD_u8DATA__XX_RAM_DATA_223                         0xDF
#define LCD_u8DATA__XX_RAM_DATA_224                         0xE0
#define LCD_u8DATA__XX_RAM_DATA_225                         0xE1
#define LCD_u8DATA__XX_RAM_DATA_226                         0xE2
#define LCD_u8DATA__XX_RAM_DATA_227                         0xE3
#define LCD_u8DATA__XX_RAM_DATA_228                         0xE4
#define LCD_u8DATA__XX_RAM_DATA_229                         0xE5
#define LCD_u8DATA__XX_RAM_DATA_230                         0xE6
#define LCD_u8DATA__XX_RAM_DATA_231                         0xE7
#define LCD_u8DATA__XX_RAM_DATA_232                         0xE8
#define LCD_u8DATA__XX_RAM_DATA_233                         0xE9
#define LCD_u8DATA__XX_RAM_DATA_234                         0xEA
#define LCD_u8DATA__XX_RAM_DATA_235                         0xEB
#define LCD_u8DATA__XX_RAM_DATA_236                         0xEC
#define LCD_u8DATA__XX_RAM_DATA_237                         0xED
#define LCD_u8DATA__XX_RAM_DATA_238                         0xEE
#define LCD_u8DATA__XX_RAM_DATA_239                         0xEF
#define LCD_u8DATA__XX_RAM_DATA_240                         0xF0
#define LCD_u8DATA__XX_RAM_DATA_241                         0xF1
#define LCD_u8DATA__XX_RAM_DATA_242                         0xF2
#define LCD_u8DATA__XX_RAM_DATA_243                         0xF3
#define LCD_u8DATA__XX_RAM_DATA_244                         0xF4
#define LCD_u8DATA__XX_RAM_DATA_245                         0xF5
#define LCD_u8DATA__XX_RAM_DATA_246                         0xF6
#define LCD_u8DATA__XX_RAM_DATA_247                         0xF7
#define LCD_u8DATA__XX_RAM_DATA_248                         0xF8
#define LCD_u8DATA__XX_RAM_DATA_249                         0xF9
#define LCD_u8DATA__XX_RAM_DATA_250                         0xFA
#define LCD_u8DATA__XX_RAM_DATA_251                         0xFB
#define LCD_u8DATA__XX_RAM_DATA_252                         0xFC
#define LCD_u8DATA__XX_RAM_DATA_253                         0xFD
#define LCD_u8DATA__XX_RAM_DATA_254                         0xFE
#define LCD_u8DATA__XX_RAM_DATA_255                         0xFF

#define LCD_u8DATA__XX_RAM_DATA_0X00                        0x00
#define LCD_u8DATA__XX_RAM_DATA_0X01                        0x01
#define LCD_u8DATA__XX_RAM_DATA_0X02                        0x02
#define LCD_u8DATA__XX_RAM_DATA_0X03                        0x03
#define LCD_u8DATA__XX_RAM_DATA_0X04                        0x04
#define LCD_u8DATA__XX_RAM_DATA_0X05                        0x05
#define LCD_u8DATA__XX_RAM_DATA_0X06                        0x06
#define LCD_u8DATA__XX_RAM_DATA_0X07                        0x07
#define LCD_u8DATA__XX_RAM_DATA_0X08                        0x08
#define LCD_u8DATA__XX_RAM_DATA_0X09                        0x09
#define LCD_u8DATA__XX_RAM_DATA_0X0A                        0x0A
#define LCD_u8DATA__XX_RAM_DATA_0X0B                        0x0B
#define LCD_u8DATA__XX_RAM_DATA_0X0C                        0x0C
#define LCD_u8DATA__XX_RAM_DATA_0X0D                        0x0D
#define LCD_u8DATA__XX_RAM_DATA_0X0E                        0x0E
#define LCD_u8DATA__XX_RAM_DATA_0X0F                        0x0F
#define LCD_u8DATA__XX_RAM_DATA_0X10                        0x10
#define LCD_u8DATA__XX_RAM_DATA_0X11                        0x11
#define LCD_u8DATA__XX_RAM_DATA_0X12                        0x12
#define LCD_u8DATA__XX_RAM_DATA_0X13                        0x13
#define LCD_u8DATA__XX_RAM_DATA_0X14                        0x14
#define LCD_u8DATA__XX_RAM_DATA_0X15                        0x15
#define LCD_u8DATA__XX_RAM_DATA_0X16                        0x16
#define LCD_u8DATA__XX_RAM_DATA_0X17                        0x17
#define LCD_u8DATA__XX_RAM_DATA_0X18                        0x18
#define LCD_u8DATA__XX_RAM_DATA_0X19                        0x19
#define LCD_u8DATA__XX_RAM_DATA_0X1A                        0x1A
#define LCD_u8DATA__XX_RAM_DATA_0X1B                        0x1B
#define LCD_u8DATA__XX_RAM_DATA_0X1C                        0x1C
#define LCD_u8DATA__XX_RAM_DATA_0X1D                        0x1D
#define LCD_u8DATA__XX_RAM_DATA_0X1E                        0x1E
#define LCD_u8DATA__XX_RAM_DATA_0X1F                        0x1F
#define LCD_u8DATA__XX_RAM_DATA_0X20                        0x20
#define LCD_u8DATA__XX_RAM_DATA_0X21                        0x21
#define LCD_u8DATA__XX_RAM_DATA_0X22                        0x22
#define LCD_u8DATA__XX_RAM_DATA_0X23                        0x23
#define LCD_u8DATA__XX_RAM_DATA_0X24                        0x24
#define LCD_u8DATA__XX_RAM_DATA_0X25                        0x25
#define LCD_u8DATA__XX_RAM_DATA_0X26                        0x26
#define LCD_u8DATA__XX_RAM_DATA_0X27                        0x27
#define LCD_u8DATA__XX_RAM_DATA_0X28                        0x28
#define LCD_u8DATA__XX_RAM_DATA_0X29                        0x29
#define LCD_u8DATA__XX_RAM_DATA_0X2A                        0x2A
#define LCD_u8DATA__XX_RAM_DATA_0X2B                        0x2B
#define LCD_u8DATA__XX_RAM_DATA_0X2C                        0x2C
#define LCD_u8DATA__XX_RAM_DATA_0X2D                        0x2D
#define LCD_u8DATA__XX_RAM_DATA_0X2E                        0x2E
#define LCD_u8DATA__XX_RAM_DATA_0X2F                        0x2F
#define LCD_u8DATA__XX_RAM_DATA_0X30                        0x30
#define LCD_u8DATA__XX_RAM_DATA_0X31                        0x31
#define LCD_u8DATA__XX_RAM_DATA_0X32                        0x32
#define LCD_u8DATA__XX_RAM_DATA_0X33                        0x33
#define LCD_u8DATA__XX_RAM_DATA_0X34                        0x34
#define LCD_u8DATA__XX_RAM_DATA_0X35                        0x35
#define LCD_u8DATA__XX_RAM_DATA_0X36                        0x36
#define LCD_u8DATA__XX_RAM_DATA_0X37                        0x37
#define LCD_u8DATA__XX_RAM_DATA_0X38                        0x38
#define LCD_u8DATA__XX_RAM_DATA_0X39                        0x39
#define LCD_u8DATA__XX_RAM_DATA_0X3A                        0x3A
#define LCD_u8DATA__XX_RAM_DATA_0X3B                        0x3B
#define LCD_u8DATA__XX_RAM_DATA_0X3C                        0x3C
#define LCD_u8DATA__XX_RAM_DATA_0X3D                        0x3D
#define LCD_u8DATA__XX_RAM_DATA_0X3E                        0x3E
#define LCD_u8DATA__XX_RAM_DATA_0X3F                        0x3F
#define LCD_u8DATA__XX_RAM_DATA_0X40                        0x40
#define LCD_u8DATA__XX_RAM_DATA_0X41                        0x41
#define LCD_u8DATA__XX_RAM_DATA_0X42                        0x42
#define LCD_u8DATA__XX_RAM_DATA_0X43                        0x43
#define LCD_u8DATA__XX_RAM_DATA_0X44                        0x44
#define LCD_u8DATA__XX_RAM_DATA_0X45                        0x45
#define LCD_u8DATA__XX_RAM_DATA_0X46                        0x46
#define LCD_u8DATA__XX_RAM_DATA_0X47                        0x47
#define LCD_u8DATA__XX_RAM_DATA_0X48                        0x48
#define LCD_u8DATA__XX_RAM_DATA_0X49                        0x49
#define LCD_u8DATA__XX_RAM_DATA_0X4A                        0x4A
#define LCD_u8DATA__XX_RAM_DATA_0X4B                        0x4B
#define LCD_u8DATA__XX_RAM_DATA_0X4C                        0x4C
#define LCD_u8DATA__XX_RAM_DATA_0X4D                        0x4D
#define LCD_u8DATA__XX_RAM_DATA_0X4E                        0x4E
#define LCD_u8DATA__XX_RAM_DATA_0X4F                        0x4F
#define LCD_u8DATA__XX_RAM_DATA_0X50                        0x50
#define LCD_u8DATA__XX_RAM_DATA_0X51                        0x51
#define LCD_u8DATA__XX_RAM_DATA_0X52                        0x52
#define LCD_u8DATA__XX_RAM_DATA_0X53                        0x53
#define LCD_u8DATA__XX_RAM_DATA_0X54                        0x54
#define LCD_u8DATA__XX_RAM_DATA_0X55                        0x55
#define LCD_u8DATA__XX_RAM_DATA_0X56                        0x56
#define LCD_u8DATA__XX_RAM_DATA_0X57                        0x57
#define LCD_u8DATA__XX_RAM_DATA_0X58                        0x58
#define LCD_u8DATA__XX_RAM_DATA_0X59                        0x59
#define LCD_u8DATA__XX_RAM_DATA_0X5A                        0x5A
#define LCD_u8DATA__XX_RAM_DATA_0X5B                        0x5B
#define LCD_u8DATA__XX_RAM_DATA_0X5C                        0x5C
#define LCD_u8DATA__XX_RAM_DATA_0X5D                        0x5D
#define LCD_u8DATA__XX_RAM_DATA_0X5E                        0x5E
#define LCD_u8DATA__XX_RAM_DATA_0X5F                        0x5F
#define LCD_u8DATA__XX_RAM_DATA_0X60                        0x60
#define LCD_u8DATA__XX_RAM_DATA_0X61                        0x61
#define LCD_u8DATA__XX_RAM_DATA_0X62                        0x62
#define LCD_u8DATA__XX_RAM_DATA_0X63                        0x63
#define LCD_u8DATA__XX_RAM_DATA_0X64                        0x64
#define LCD_u8DATA__XX_RAM_DATA_0X65                        0x65
#define LCD_u8DATA__XX_RAM_DATA_0X66                        0x66
#define LCD_u8DATA__XX_RAM_DATA_0X67                        0x67
#define LCD_u8DATA__XX_RAM_DATA_0X68                        0x68
#define LCD_u8DATA__XX_RAM_DATA_0X69                        0x69
#define LCD_u8DATA__XX_RAM_DATA_0X6A                        0x6A
#define LCD_u8DATA__XX_RAM_DATA_0X6B                        0x6B
#define LCD_u8DATA__XX_RAM_DATA_0X6C                        0x6C
#define LCD_u8DATA__XX_RAM_DATA_0X6D                        0x6D
#define LCD_u8DATA__XX_RAM_DATA_0X6E                        0x6E
#define LCD_u8DATA__XX_RAM_DATA_0X6F                        0x6F
#define LCD_u8DATA__XX_RAM_DATA_0X70                        0x70
#define LCD_u8DATA__XX_RAM_DATA_0X71                        0x71
#define LCD_u8DATA__XX_RAM_DATA_0X72                        0x72
#define LCD_u8DATA__XX_RAM_DATA_0X73                        0x73
#define LCD_u8DATA__XX_RAM_DATA_0X74                        0x74
#define LCD_u8DATA__XX_RAM_DATA_0X75                        0x75
#define LCD_u8DATA__XX_RAM_DATA_0X76                        0x76
#define LCD_u8DATA__XX_RAM_DATA_0X77                        0x77
#define LCD_u8DATA__XX_RAM_DATA_0X78                        0x78
#define LCD_u8DATA__XX_RAM_DATA_0X79                        0x79
#define LCD_u8DATA__XX_RAM_DATA_0X7A                        0x7A
#define LCD_u8DATA__XX_RAM_DATA_0X7B                        0x7B
#define LCD_u8DATA__XX_RAM_DATA_0X7C                        0x7C
#define LCD_u8DATA__XX_RAM_DATA_0X7D                        0x7D
#define LCD_u8DATA__XX_RAM_DATA_0X7E                        0x7E
#define LCD_u8DATA__XX_RAM_DATA_0X7F                        0x7F
#define LCD_u8DATA__XX_RAM_DATA_0X80                        0x80
#define LCD_u8DATA__XX_RAM_DATA_0X81                        0x81
#define LCD_u8DATA__XX_RAM_DATA_0X82                        0x82
#define LCD_u8DATA__XX_RAM_DATA_0X83                        0x83
#define LCD_u8DATA__XX_RAM_DATA_0X84                        0x84
#define LCD_u8DATA__XX_RAM_DATA_0X85                        0x85
#define LCD_u8DATA__XX_RAM_DATA_0X86                        0x86
#define LCD_u8DATA__XX_RAM_DATA_0X87                        0x87
#define LCD_u8DATA__XX_RAM_DATA_0X88                        0x88
#define LCD_u8DATA__XX_RAM_DATA_0X89                        0x89
#define LCD_u8DATA__XX_RAM_DATA_0X8A                        0x8A
#define LCD_u8DATA__XX_RAM_DATA_0X8B                        0x8B
#define LCD_u8DATA__XX_RAM_DATA_0X8C                        0x8C
#define LCD_u8DATA__XX_RAM_DATA_0X8D                        0x8D
#define LCD_u8DATA__XX_RAM_DATA_0X8E                        0x8E
#define LCD_u8DATA__XX_RAM_DATA_0X8F                        0x8F
#define LCD_u8DATA__XX_RAM_DATA_0X90                        0x90
#define LCD_u8DATA__XX_RAM_DATA_0X91                        0x91
#define LCD_u8DATA__XX_RAM_DATA_0X92                        0x92
#define LCD_u8DATA__XX_RAM_DATA_0X93                        0x93
#define LCD_u8DATA__XX_RAM_DATA_0X94                        0x94
#define LCD_u8DATA__XX_RAM_DATA_0X95                        0x95
#define LCD_u8DATA__XX_RAM_DATA_0X96                        0x96
#define LCD_u8DATA__XX_RAM_DATA_0X97                        0x97
#define LCD_u8DATA__XX_RAM_DATA_0X98                        0x98
#define LCD_u8DATA__XX_RAM_DATA_0X99                        0x99
#define LCD_u8DATA__XX_RAM_DATA_0X9A                        0x9A
#define LCD_u8DATA__XX_RAM_DATA_0X9B                        0x9B
#define LCD_u8DATA__XX_RAM_DATA_0X9C                        0x9C
#define LCD_u8DATA__XX_RAM_DATA_0X9D                        0x9D
#define LCD_u8DATA__XX_RAM_DATA_0X9E                        0x9E
#define LCD_u8DATA__XX_RAM_DATA_0X9F                        0x9F
#define LCD_u8DATA__XX_RAM_DATA_0XA0                        0xA0
#define LCD_u8DATA__XX_RAM_DATA_0XA1                        0xA1
#define LCD_u8DATA__XX_RAM_DATA_0XA2                        0xA2
#define LCD_u8DATA__XX_RAM_DATA_0XA3                        0xA3
#define LCD_u8DATA__XX_RAM_DATA_0XA4                        0xA4
#define LCD_u8DATA__XX_RAM_DATA_0XA5                        0xA5
#define LCD_u8DATA__XX_RAM_DATA_0XA6                        0xA6
#define LCD_u8DATA__XX_RAM_DATA_0XA7                        0xA7
#define LCD_u8DATA__XX_RAM_DATA_0XA8                        0xA8
#define LCD_u8DATA__XX_RAM_DATA_0XA9                        0xA9
#define LCD_u8DATA__XX_RAM_DATA_0XAA                        0xAA
#define LCD_u8DATA__XX_RAM_DATA_0XAB                        0xAB
#define LCD_u8DATA__XX_RAM_DATA_0XAC                        0xAC
#define LCD_u8DATA__XX_RAM_DATA_0XAD                        0xAD
#define LCD_u8DATA__XX_RAM_DATA_0XAE                        0xAE
#define LCD_u8DATA__XX_RAM_DATA_0XAF                        0xAF
#define LCD_u8DATA__XX_RAM_DATA_0XB0                        0xB0
#define LCD_u8DATA__XX_RAM_DATA_0XB1                        0xB1
#define LCD_u8DATA__XX_RAM_DATA_0XB2                        0xB2
#define LCD_u8DATA__XX_RAM_DATA_0XB3                        0xB3
#define LCD_u8DATA__XX_RAM_DATA_0XB4                        0xB4
#define LCD_u8DATA__XX_RAM_DATA_0XB5                        0xB5
#define LCD_u8DATA__XX_RAM_DATA_0XB6                        0xB6
#define LCD_u8DATA__XX_RAM_DATA_0XB7                        0xB7
#define LCD_u8DATA__XX_RAM_DATA_0XB8                        0xB8
#define LCD_u8DATA__XX_RAM_DATA_0XB9                        0xB9
#define LCD_u8DATA__XX_RAM_DATA_0XBA                        0xBA
#define LCD_u8DATA__XX_RAM_DATA_0XBB                        0xBB
#define LCD_u8DATA__XX_RAM_DATA_0XBC                        0xBC
#define LCD_u8DATA__XX_RAM_DATA_0XBD                        0xBD
#define LCD_u8DATA__XX_RAM_DATA_0XBE                        0xBE
#define LCD_u8DATA__XX_RAM_DATA_0XBF                        0xBF
#define LCD_u8DATA__XX_RAM_DATA_0XC0                        0xC0
#define LCD_u8DATA__XX_RAM_DATA_0XC1                        0xC1
#define LCD_u8DATA__XX_RAM_DATA_0XC2                        0xC2
#define LCD_u8DATA__XX_RAM_DATA_0XC3                        0xC3
#define LCD_u8DATA__XX_RAM_DATA_0XC4                        0xC4
#define LCD_u8DATA__XX_RAM_DATA_0XC5                        0xC5
#define LCD_u8DATA__XX_RAM_DATA_0XC6                        0xC6
#define LCD_u8DATA__XX_RAM_DATA_0XC7                        0xC7
#define LCD_u8DATA__XX_RAM_DATA_0XC8                        0xC8
#define LCD_u8DATA__XX_RAM_DATA_0XC9                        0xC9
#define LCD_u8DATA__XX_RAM_DATA_0XCA                        0xCA
#define LCD_u8DATA__XX_RAM_DATA_0XCB                        0xCB
#define LCD_u8DATA__XX_RAM_DATA_0XCC                        0xCC
#define LCD_u8DATA__XX_RAM_DATA_0XCD                        0xCD
#define LCD_u8DATA__XX_RAM_DATA_0XCE                        0xCE
#define LCD_u8DATA__XX_RAM_DATA_0XCF                        0xCF
#define LCD_u8DATA__XX_RAM_DATA_0XD0                        0xD0
#define LCD_u8DATA__XX_RAM_DATA_0XD1                        0xD1
#define LCD_u8DATA__XX_RAM_DATA_0XD2                        0xD2
#define LCD_u8DATA__XX_RAM_DATA_0XD3                        0xD3
#define LCD_u8DATA__XX_RAM_DATA_0XD4                        0xD4
#define LCD_u8DATA__XX_RAM_DATA_0XD5                        0xD5
#define LCD_u8DATA__XX_RAM_DATA_0XD6                        0xD6
#define LCD_u8DATA__XX_RAM_DATA_0XD7                        0xD7
#define LCD_u8DATA__XX_RAM_DATA_0XD8                        0xD8
#define LCD_u8DATA__XX_RAM_DATA_0XD9                        0xD9
#define LCD_u8DATA__XX_RAM_DATA_0XDA                        0xDA
#define LCD_u8DATA__XX_RAM_DATA_0XDB                        0xDB
#define LCD_u8DATA__XX_RAM_DATA_0XDC                        0xDC
#define LCD_u8DATA__XX_RAM_DATA_0XDD                        0xDD
#define LCD_u8DATA__XX_RAM_DATA_0XDE                        0xDE
#define LCD_u8DATA__XX_RAM_DATA_0XDF                        0xDF
#define LCD_u8DATA__XX_RAM_DATA_0XE0                        0xE0
#define LCD_u8DATA__XX_RAM_DATA_0XE1                        0xE1
#define LCD_u8DATA__XX_RAM_DATA_0XE2                        0xE2
#define LCD_u8DATA__XX_RAM_DATA_0XE3                        0xE3
#define LCD_u8DATA__XX_RAM_DATA_0XE4                        0xE4
#define LCD_u8DATA__XX_RAM_DATA_0XE5                        0xE5
#define LCD_u8DATA__XX_RAM_DATA_0XE6                        0xE6
#define LCD_u8DATA__XX_RAM_DATA_0XE7                        0xE7
#define LCD_u8DATA__XX_RAM_DATA_0XE8                        0xE8
#define LCD_u8DATA__XX_RAM_DATA_0XE9                        0xE9
#define LCD_u8DATA__XX_RAM_DATA_0XEA                        0xEA
#define LCD_u8DATA__XX_RAM_DATA_0XEB                        0xEB
#define LCD_u8DATA__XX_RAM_DATA_0XEC                        0xEC
#define LCD_u8DATA__XX_RAM_DATA_0XED                        0xED
#define LCD_u8DATA__XX_RAM_DATA_0XEE                        0xEE
#define LCD_u8DATA__XX_RAM_DATA_0XEF                        0xEF
#define LCD_u8DATA__XX_RAM_DATA_0XF0                        0xF0
#define LCD_u8DATA__XX_RAM_DATA_0XF1                        0xF1
#define LCD_u8DATA__XX_RAM_DATA_0XF2                        0xF2
#define LCD_u8DATA__XX_RAM_DATA_0XF3                        0xF3
#define LCD_u8DATA__XX_RAM_DATA_0XF4                        0xF4
#define LCD_u8DATA__XX_RAM_DATA_0XF5                        0xF5
#define LCD_u8DATA__XX_RAM_DATA_0XF6                        0xF6
#define LCD_u8DATA__XX_RAM_DATA_0XF7                        0xF7
#define LCD_u8DATA__XX_RAM_DATA_0XF8                        0xF8
#define LCD_u8DATA__XX_RAM_DATA_0XF9                        0xF9
#define LCD_u8DATA__XX_RAM_DATA_0XFA                        0xFA
#define LCD_u8DATA__XX_RAM_DATA_0XFB                        0xFB
#define LCD_u8DATA__XX_RAM_DATA_0XFC                        0xFC
#define LCD_u8DATA__XX_RAM_DATA_0XFD                        0xFD
#define LCD_u8DATA__XX_RAM_DATA_0XFE                        0xFE
#define LCD_u8DATA__XX_RAM_DATA_0XFF                        0xFF

#define LCD_u8DATA__XX_RAM_DATA_SPACE   				     0x20
#define LCD_u8DATA__XX_RAM_DATA_EXCLAMATION_MARK            0x21
#define LCD_u8DATA__XX_RAM_DATA_DOUBLE_QUOTE                0x22
#define LCD_u8DATA__XX_RAM_DATA_HASH                        0x23
#define LCD_u8DATA__XX_RAM_DATA_DOLLAR                      0x24
#define LCD_u8DATA__XX_RAM_DATA_PERCENTAGE                  0x25
#define LCD_u8DATA__XX_RAM_DATA_AND                         0x26
#define LCD_u8DATA__XX_RAM_DATA_SINGLE_QUOTE                0x27
#define LCD_u8DATA__XX_RAM_DATA_OPENING_BRACKET             0x28
#define LCD_u8DATA__XX_RAM_DATA_CLOSINGING_BRACKET          0x29
#define LCD_u8DATA__XX_RAM_DATA_MULT                        0x2A
#define LCD_u8DATA__XX_RAM_DATA_PLUS                        0x2B
#define LCD_u8DATA__XX_RAM_DATA_COMMA                       0x2C
#define LCD_u8DATA__XX_RAM_DATA_MINUS                       0x2D
#define LCD_u8DATA__XX_RAM_DATA_DOT                         0x2E
#define LCD_u8DATA__XX_RAM_DATA_FORWARD_SLASH               0x2F
#define LCD_u8DATA__XX_RAM_DATA_ASCII_0                     0x30
#define LCD_u8DATA__XX_RAM_DATA_ASCII_1                     0x31
#define LCD_u8DATA__XX_RAM_DATA_ASCII_2                     0x32
#define LCD_u8DATA__XX_RAM_DATA_ASCII_3                     0x33
#define LCD_u8DATA__XX_RAM_DATA_ASCII_4                     0x34
#define LCD_u8DATA__XX_RAM_DATA_ASCII_5                     0x35
#define LCD_u8DATA__XX_RAM_DATA_ASCII_6                     0x36
#define LCD_u8DATA__XX_RAM_DATA_ASCII_7                     0x37
#define LCD_u8DATA__XX_RAM_DATA_ASCII_8                     0x38
#define LCD_u8DATA__XX_RAM_DATA_ASCII_9                     0x39
#define LCD_u8DATA__XX_RAM_DATA_COLON                       0x3A
#define LCD_u8DATA__XX_RAM_DATA_SEMICOLON                   0x3B
#define LCD_u8DATA__XX_RAM_DATA_LESS_THAN                   0x3C
#define LCD_u8DATA__XX_RAM_DATA_EQUAL                       0x3D
#define LCD_u8DATA__XX_RAM_DATA_BIGGER_THAN                 0x3E
#define LCD_u8DATA__XX_RAM_DATA_QUESTION_MARK               0x3F
#define LCD_u8DATA__XX_RAM_DATA_AT_MARK                     0x40
#define LCD_u8DATA__XX_RAM_DATA_A                           0x41
#define LCD_u8DATA__XX_RAM_DATA_B                           0x42
#define LCD_u8DATA__XX_RAM_DATA_C                           0x43
#define LCD_u8DATA__XX_RAM_DATA_D                           0x44
#define LCD_u8DATA__XX_RAM_DATA_E                           0x45
#define LCD_u8DATA__XX_RAM_DATA_F                           0x46
#define LCD_u8DATA__XX_RAM_DATA_G                           0x47
#define LCD_u8DATA__XX_RAM_DATA_H                           0x48
#define LCD_u8DATA__XX_RAM_DATA_I                           0x49
#define LCD_u8DATA__XX_RAM_DATA_J                           0x4A
#define LCD_u8DATA__XX_RAM_DATA_K                           0x4B
#define LCD_u8DATA__XX_RAM_DATA_L                           0x4C
#define LCD_u8DATA__XX_RAM_DATA_M                           0x4D
#define LCD_u8DATA__XX_RAM_DATA_N                           0x4E
#define LCD_u8DATA__XX_RAM_DATA_O                           0x4F
#define LCD_u8DATA__XX_RAM_DATA_P                           0x50
#define LCD_u8DATA__XX_RAM_DATA_Q                           0x51
#define LCD_u8DATA__XX_RAM_DATA_R                           0x52
#define LCD_u8DATA__XX_RAM_DATA_S                           0x53
#define LCD_u8DATA__XX_RAM_DATA_T                           0x54
#define LCD_u8DATA__XX_RAM_DATA_U                           0x55
#define LCD_u8DATA__XX_RAM_DATA_V                           0x56
#define LCD_u8DATA__XX_RAM_DATA_W                           0x57
#define LCD_u8DATA__XX_RAM_DATA_X                           0x58
#define LCD_u8DATA__XX_RAM_DATA_Y                           0x59
#define LCD_u8DATA__XX_RAM_DATA_Z                           0x5A
#define LCD_u8DATA__XX_RAM_DATA_SOLID_BRACKET_OPEN          0x5B
#define LCD_u8DATA__XX_RAM_DATA_BACK_SLASH                  0x5C
#define LCD_u8DATA__XX_RAM_DATA_SOLID_BRACKET_CLOSE         0x5D
#define LCD_u8DATA__XX_RAM_DATA_CAP                         0x5E
#define LCD_u8DATA__XX_RAM_DATA_UNDERSCORE                  0x5F
#define LCD_u8DATA__XX_RAM_DATA_BACKTICK                    0x60
#define LCD_u8DATA__XX_RAM_DATA_a                           0x61
#define LCD_u8DATA__XX_RAM_DATA_b                           0x62
#define LCD_u8DATA__XX_RAM_DATA_c                           0x63
#define LCD_u8DATA__XX_RAM_DATA_d                           0x64
#define LCD_u8DATA__XX_RAM_DATA_e                           0x65
#define LCD_u8DATA__XX_RAM_DATA_f                           0x66
#define LCD_u8DATA__XX_RAM_DATA_g                           0x67
#define LCD_u8DATA__XX_RAM_DATA_h                           0x68
#define LCD_u8DATA__XX_RAM_DATA_i                           0x69
#define LCD_u8DATA__XX_RAM_DATA_j                           0x6A
#define LCD_u8DATA__XX_RAM_DATA_k                           0x6B
#define LCD_u8DATA__XX_RAM_DATA_l                           0x6C
#define LCD_u8DATA__XX_RAM_DATA_m                           0x6D
#define LCD_u8DATA__XX_RAM_DATA_n                           0x6E
#define LCD_u8DATA__XX_RAM_DATA_o                           0x6F
#define LCD_u8DATA__XX_RAM_DATA_p                           0x70
#define LCD_u8DATA__XX_RAM_DATA_q                           0x71
#define LCD_u8DATA__XX_RAM_DATA_r                           0x72
#define LCD_u8DATA__XX_RAM_DATA_s                           0x73
#define LCD_u8DATA__XX_RAM_DATA_t                           0x74
#define LCD_u8DATA__XX_RAM_DATA_u                           0x75
#define LCD_u8DATA__XX_RAM_DATA_v                           0x76
#define LCD_u8DATA__XX_RAM_DATA_w                           0x77
#define LCD_u8DATA__XX_RAM_DATA_x                           0x78
#define LCD_u8DATA__XX_RAM_DATA_y                           0x79
#define LCD_u8DATA__XX_RAM_DATA_z                           0x7A
#define LCD_u8DATA__XX_RAM_DATA_CURLY_BRACKET_OPEN          0x7B
#define LCD_u8DATA__XX_RAM_DATA_BAR                         0x7C
#define LCD_u8DATA__XX_RAM_DATA_CURLY_BRACKET_CLOSE         0x7D
#define LCD_u8DATA__XX_RAM_DATA_TILDA                       0x7E

#define LCD_u8SEND_TYPE_CMD                                 0x00
#define LCD_u8SEND_TYPE_DATA                                0x02

#define LCD_u8DISPLAY_NUMBER_PRECISION_1                    10
#define LCD_u8DISPLAY_NUMBER_PRECISION_2                    100
#define LCD_u8DISPLAY_NUMBER_PRECISION_3                    1000
#define LCD_u8DISPLAY_NUMBER_PRECISION_4                    10000
#define LCD_u8DISPLAY_NUMBER_PRECISION_5                    100000

typedef enum{
    Lcd_enuOK,
    Lcd_enuInvalidCmdError,
    Lcd_enuInvalidCharError,
} Lcd_tenuErrorStatus;

void Lcd_vidInit(void);
Lcd_tenuErrorStatus Lcd_enuSend(u8 Copy_u8SendType, u8 Copy_u8Cmd);
Lcd_tenuErrorStatus Lcd_enuGoto(u8 Copy_u8XPos, u8 Copy_u8YPos);
Lcd_tenuErrorStatus Lcd_enuDisplayNumber(s32 Copy_u32Num);
Lcd_tenuErrorStatus Lcd_enuDisplayNumberR2L(u32 Copy_u32Num);
Lcd_tenuErrorStatus Lcd_enuDisplayFloatNumber(f32 Copy_f32Num, u32 Copy_u32Pre);
Lcd_tenuErrorStatus Lcd_enuDisplayFloatNumberR2L(f32 Copy_f32Num, u32 Copy_u32Pre); // not implemented yet
Lcd_tenuErrorStatus Lcd_enuDisplayString(u8 Copy_au8String[]);
Lcd_tenuErrorStatus Lcd_enuCreateCustomCharacter(u8 Copy_au8CharArray[], u8 Copy_u8ShapeIndex);

#endif /* LCD_H_ */
